export const demoMenuItems = [
  {
    id: 1,
    name: "Chicken Luwombo",
    price: "18000",
    description: "Slow-cooked chicken steamed in banana leaves with rich groundnut sauce.",
    category_name: "Luwombo",
    category: 1,
    variants: [
      { id: 1, name: "Regular", price: "18000" },
      { id: 2, name: "Large", price: "24000" },
    ],
    modifier_groups: [
      {
        id: 1,
        name: "Add a side",
        options: [
          { id: 1, name: "Extra matooke", price_delta: "3000" },
          { id: 2, name: "Rice", price_delta: "2500" },
        ],
      },
    ],
    popular: true,
  },
  {
    id: 2,
    name: "Beef Luwombo",
    price: "20000",
    description: "Tender beef simmered in a traditional banana-leaf parcel.",
    category_name: "Luwombo",
    category: 1,
    variants: [],
    modifier_groups: [],
    popular: true,
  },
  {
    id: 3,
    name: "Local Fish Plate",
    price: "26000",
    description: "Seasoned fish served with greens, matooke and a fresh tomato relish.",
    category_name: "Local plates",
    category: 2,
    variants: [],
    modifier_groups: [
      {
        id: 2,
        name: "Add a side",
        options: [{ id: 3, name: "Extra matooke", price_delta: "3000" }],
      },
    ],
    popular: true,
  },
  {
    id: 4,
    name: "Beef Stew Plate",
    price: "18000",
    description: "Hearty beef stew with your choice of rice, posho or matooke.",
    category_name: "Local plates",
    category: 2,
    variants: [],
    modifier_groups: [],
    popular: false,
  },
  {
    id: 5,
    name: "Goat Pilau",
    price: "22000",
    description: "Fragrant spiced rice with tender goat and kachumbari.",
    category_name: "Local plates",
    category: 2,
    variants: [],
    modifier_groups: [],
    popular: true,
  },
  {
    id: 6,
    name: "Chicken Rolex",
    price: "9000",
    description: "A freshly rolled chapati with egg, chicken and crisp vegetables.",
    category_name: "Quick bites",
    category: 3,
    variants: [],
    modifier_groups: [],
    popular: false,
  },
  {
    id: 7,
    name: "Samosas",
    price: "6000",
    description: "Three golden, crisp samosas with a gently spiced filling.",
    category_name: "Quick bites",
    category: 3,
    variants: [],
    modifier_groups: [],
    popular: false,
  },
  {
    id: 8,
    name: "Fresh Passion Juice",
    price: "5000",
    description: "Freshly blended passion fruit juice, served chilled.",
    category_name: "Drinks",
    category: 4,
    variants: [
      { id: 3, name: "Regular", price: "5000" },
      { id: 4, name: "Large", price: "7000" },
    ],
    modifier_groups: [],
    popular: true,
  },
  {
    id: 9,
    name: "African Tea",
    price: "4000",
    description: "Comforting spiced tea with milk.",
    category_name: "Drinks",
    category: 4,
    variants: [],
    modifier_groups: [],
    popular: false,
  },
];

export const demoDeliveryZones = [
  { id: 1, name: "Kampala Central", fee: 2500 },
  { id: 2, name: "Ntinda", fee: 4000 },
  { id: 3, name: "Bugolobi", fee: 4000 },
  { id: 4, name: "Najjanankumbi", fee: 5000 },
];